// `no_main` is required for WASM / Stylus builds, but must not be set when
// the test harness or export-abi feature need a `main` entry-point.
#![cfg_attr(all(target_arch = "wasm32", not(feature = "export-abi")), no_main)]

// `alloc` is a no_std dependency — only needed on the WASM target.
#[cfg(target_arch = "wasm32")]
extern crate alloc;

/// Pure business-logic module.
///
/// Contains zero EVM host calls, so it compiles and runs on the native target
/// (`cargo test`) without any Stylus / WASM environment.
///
/// All unit tests live inside this module.
pub mod logic;

// ─────────────────────────────────────────────────────────────────────────────
// Contract code — compiled ONLY on the `wasm32-unknown-unknown` target.
//
// `cargo stylus check` and `cargo stylus export-abi` both target wasm32, so
// they compile this block and see the full `#[public]` interface.
//
// `cargo test` runs on the native host (e.g. x86_64-unknown-linux-gnu).
// On the native target neither `alloy_sol_types 0.7.6` exposes
// `private::IntoLogData` (needed by the sol! macro expansion generated by
// alloy-sol-macro 0.7.7), nor are the Stylus host symbols available.
// By gating on `target_arch = "wasm32"`, the native build only compiles the
// pure `logic` module, allowing `cargo test` to succeed without EVM context.
// ─────────────────────────────────────────────────────────────────────────────
#[cfg(target_arch = "wasm32")]
mod contract {
    use super::logic;
    use alloy_primitives::{Address, U256};
    use alloy_sol_types::sol;
    use logic::{
        refund_per_participant, resolve_payout, total_pool, validate_confirm_result,
        validate_deposit, validate_refund, STATE_ABIERTO, STATE_BLOQUEADO, STATE_REEMBOLSADO,
        STATE_RESUELTO,
    };
    use stylus_sdk::{
        call::transfer_eth,
        evm, msg,
        prelude::*,
        storage::{StorageAddress, StorageBool, StorageMap, StorageU256, StorageU8},
    };

    // ── On-chain events ───────────────────────────────────────────────────────

    sol! {
        event ChallengeCreated(
            uint256 indexed challenge_id,
            address indexed creator,
            uint256 required_deposit,
            uint256 deadline
        );
        event DepositReceived(
            uint256 indexed challenge_id,
            address indexed participant,
            uint256 amount
        );
        event ChallengeLocked(
            uint256 indexed challenge_id,
            uint256 treasury_shares
        );
        event ChallengeResolved(
            uint256 indexed challenge_id,
            address indexed winner,
            uint256 total_payout,
            uint256 commission
        );
        event ChallengeRefunded(
            uint256 indexed challenge_id,
            uint256 refund_per_participant
        );
        event OperatorAdded(address indexed operator);
        event OperatorRemoved(address indexed operator);
    }

    // ── Storage ───────────────────────────────────────────────────────────────

    #[storage]
    pub struct Challenge {
        pub creator: StorageAddress,
        pub required_deposit: StorageU256,
        pub deadline: StorageU256,
        pub status: StorageU8,
        pub winner: StorageAddress,
        pub treasury_shares: StorageU256,
        pub participant_count: StorageU256,
        pub deposited_count: StorageU256,
        pub participants: StorageMap<Address, StorageBool>,
        pub has_deposited: StorageMap<Address, StorageBool>,
    }

    #[storage]
    #[entrypoint]
    pub struct ChallengePool {
        pub challenges: StorageMap<U256, Challenge>,
        pub next_challenge_id: StorageU256,
        pub treasury_vault: StorageAddress,
        /// Authorized operators (Cloudflare Worker account, SDD §9).
        pub operators: StorageMap<Address, StorageBool>,
        /// Commission rate in basis points (e.g. 500 = 5 %).
        pub base_commission_rate: StorageU256,
        /// Contract owner / admin.
        pub owner: StorageAddress,
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    impl ChallengePool {
        /// Reverts if the caller is not an authorized operator (SDD §11).
        fn require_operator(&self) -> Result<(), Vec<u8>> {
            if !self.operators.get(msg::sender()) {
                return Err(b"not_an_operator".to_vec());
            }
            Ok(())
        }

        /// Reverts if the caller is not the owner.
        fn require_owner(&self) -> Result<(), Vec<u8>> {
            if msg::sender() != self.owner.get() {
                return Err(b"not_owner".to_vec());
            }
            Ok(())
        }
    }

    // ── Public interface ──────────────────────────────────────────────────────

    #[public]
    impl ChallengePool {
        // ── Admin / initialization ─────────────────────────────────────────

        /// One-shot initializer. Sets the owner to msg::sender.
        /// Must be called immediately after deployment.
        pub fn init(
            &mut self,
            treasury_vault: Address,
            base_commission_rate: U256,
        ) -> Result<(), Vec<u8>> {
            if self.owner.get() != Address::ZERO {
                return Err(b"already_initialized".to_vec());
            }
            self.owner.set(msg::sender());
            self.treasury_vault.set(treasury_vault);
            self.base_commission_rate.set(base_commission_rate);
            Ok(())
        }

        /// Add an authorized operator. Owner-only.
        pub fn add_operator(&mut self, operator: Address) -> Result<(), Vec<u8>> {
            self.require_owner()?;
            if operator == Address::ZERO {
                return Err(b"operator_is_zero".to_vec());
            }
            self.operators.setter(operator).set(true);
            evm::log(OperatorAdded { operator });
            Ok(())
        }

        /// Remove an authorized operator. Owner-only.
        pub fn remove_operator(&mut self, operator: Address) -> Result<(), Vec<u8>> {
            self.require_owner()?;
            self.operators.setter(operator).set(false);
            evm::log(OperatorRemoved { operator });
            Ok(())
        }

        /// Update commission rate (max 10 % = 1 000 bps). Owner-only.
        pub fn set_commission_rate(&mut self, rate_bps: U256) -> Result<(), Vec<u8>> {
            self.require_owner()?;
            if rate_bps > U256::from(1_000u64) {
                return Err(b"rate_too_high".to_vec());
            }
            self.base_commission_rate.set(rate_bps);
            Ok(())
        }

        // ── Challenge lifecycle ────────────────────────────────────────────

        /// Create a new challenge in state Abierto (SDD §6.3.1).
        pub fn create_challenge(
            &mut self,
            required_deposit: U256,
            deadline: U256,
            participants_list: Vec<Address>,
        ) -> Result<U256, Vec<u8>> {
            if participants_list.is_empty() {
                return Err(b"no_participants".to_vec());
            }
            if required_deposit.is_zero() {
                return Err(b"zero_deposit".to_vec());
            }
            if required_deposit > U256::from(logic::MAX_DEPOSIT_WEI) {
                return Err(b"deposit_exceeds_maximum".to_vec());
            }

            let challenge_id = self.next_challenge_id.get();
            self.next_challenge_id.set(challenge_id + U256::from(1u8));

            {
                let mut ch = self.challenges.setter(challenge_id);
                ch.creator.set(msg::sender());
                ch.required_deposit.set(required_deposit);
                ch.deadline.set(deadline);
                ch.status.set(STATE_ABIERTO);
                ch.participant_count.set(U256::from(participants_list.len()));
                ch.deposited_count.set(U256::ZERO);

                for p in participants_list.iter() {
                    ch.participants.setter(*p).set(true);
                    ch.has_deposited.setter(*p).set(false);
                }
            }

            evm::log(ChallengeCreated {
                challenge_id,
                creator: msg::sender(),
                required_deposit,
                deadline,
            });

            Ok(challenge_id)
        }

        /// Deposit for a challenge. Caller must send exactly `required_deposit`.
        ///
        /// Security: CEI — all state written BEFORE external interactions.
        #[payable]
        pub fn deposit(&mut self, challenge_id: U256) -> Result<(), Vec<u8>> {
            let amount = msg::value();
            let sender = msg::sender();

            // CHECKS
            let (status, is_participant, already_deposited, required_deposit, deposited_count, participant_count) = {
                let ch = self.challenges.setter(challenge_id);
                (
                    ch.status.get(),
                    ch.participants.get(sender),
                    ch.has_deposited.get(sender),
                    ch.required_deposit.get(),
                    ch.deposited_count.get(),
                    ch.participant_count.get(),
                )
            };

            validate_deposit(status, is_participant, already_deposited, amount, required_deposit)
                .map_err(|e| e.as_bytes().to_vec())?;

            // EFFECTS — state written before any external call
            let new_deposited = deposited_count + U256::from(1u8);
            {
                let mut ch = self.challenges.setter(challenge_id);
                ch.has_deposited.setter(sender).set(true);
                ch.deposited_count.set(new_deposited);

                evm::log(DepositReceived {
                    challenge_id,
                    participant: sender,
                    amount,
                });

                if new_deposited == participant_count {
                    // MVP: 1:1 shares. Production: call treasury_vault.deposit().
                    let shares = total_pool(required_deposit, participant_count);
                    ch.status.set(STATE_BLOQUEADO);
                    ch.treasury_shares.set(shares);

                    evm::log(ChallengeLocked {
                        challenge_id,
                        treasury_shares: shares,
                    });
                }
            }

            // INTERACTIONS: none at deposit time (ETH stays in contract).
            Ok(())
        }

        /// Relay the consensus winner and resolve the challenge. Operator-only.
        ///
        /// Security (SDD §11):
        ///   - `require_operator()` reverts if caller is not authorized.
        ///   - Winner cannot be zero address.
        ///   - State → Resuelto BEFORE the ETH transfer (CEI).
        ///   - The operator has no path to redirect funds to an arbitrary address;
        ///     ETH is transferred exclusively to `winner`.
        pub fn confirm_result(
            &mut self,
            challenge_id: U256,
            winner: Address,
        ) -> Result<(), Vec<u8>> {
            // CHECKS
            self.require_operator()?;

            let (status, treasury_shares) = {
                let ch = self.challenges.setter(challenge_id);
                (ch.status.get(), ch.treasury_shares.get())
            };

            validate_confirm_result(status, winner)
                .map_err(|e| e.as_bytes().to_vec())?;

            let rate = self.base_commission_rate.get();
            // MVP: mock 5 % yield (SDD §7.4 — real value from TreasuryVault in production).
            let yield_rate = U256::from(500u64);
            let (winner_payout, commission) = resolve_payout(treasury_shares, yield_rate, rate);

            // EFFECTS — mark terminal state before ETH transfer prevents reentrancy.
            {
                let mut ch = self.challenges.setter(challenge_id);
                ch.status.set(STATE_RESUELTO);
                ch.winner.set(winner);
            }

            evm::log(ChallengeResolved {
                challenge_id,
                winner,
                total_payout: winner_payout,
                commission,
            });

            // INTERACTIONS — ETH transfer after all state changes.
            transfer_eth(winner, winner_payout)
                .map_err(|_| b"transfer_failed".to_vec())?;

            Ok(())
        }

        /// Refund participants after deadline without consensus (SDD §8.3, §6.3.4).
        ///
        /// No commission. Permissionless once deadline has elapsed.
        /// Security: state → Reembolsado BEFORE any external interaction (CEI).
        pub fn refund(&mut self, challenge_id: U256) -> Result<(), Vec<u8>> {
            // CHECKS
            let (status, treasury_shares, participant_count, deadline) = {
                let ch = self.challenges.setter(challenge_id);
                (
                    ch.status.get(),
                    ch.treasury_shares.get(),
                    ch.participant_count.get(),
                    ch.deadline.get(),
                )
            };

            let now = U256::from(stylus_sdk::block::timestamp());
            validate_refund(status, deadline, now)
                .map_err(|e| e.as_bytes().to_vec())?;

            let per_participant = refund_per_participant(treasury_shares, participant_count);

            // EFFECTS
            {
                let mut ch = self.challenges.setter(challenge_id);
                ch.status.set(STATE_REEMBOLSADO);
            }

            evm::log(ChallengeRefunded {
                challenge_id,
                refund_per_participant: per_participant,
            });

            // INTERACTIONS: pull-payment flow deferred to follow-up (SDD §15 roadmap).
            Ok(())
        }

        // ── Read-only helpers ──────────────────────────────────────────────

        /// Returns the current status byte of a challenge.
        pub fn challenge_status(&self, challenge_id: U256) -> Result<u8, Vec<u8>> {
            Ok(self.challenges.getter(challenge_id).status.get())
        }

        /// Returns true if `operator` is authorized.
        pub fn is_operator(&self, operator: Address) -> Result<bool, Vec<u8>> {
            Ok(self.operators.get(operator))
        }
    }
}
