name = "otter-pot-sweeper"
main = "src/index.ts"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 */12 * * *"]

[vars]
ENVIRONMENT = "development"
CHAIN_ID = "421614"         # Arbitrum Sepolia
SWEEP_THRESHOLD_USDC = "10"
